version: '2'
services:
    slap-app:
        image: slap
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://slap-postgresql:5432/slap
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    slap-postgresql:
        extends:
            file: postgresql.yml
            service: slap-postgresql
